//This can easily be done. However, it's helpful to have a disk/machine image file you could build a scaleset from beforehand. For example....
//https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/quick-create-bicep-windows?tabs=CLI
